name: Cancer ML CI/CD DOCKER

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train the Model
      run: python model/train.py

    - name: Run Tests
      run: pytest test/

    - name: Check Model Accuracy
      run: python test/test_model.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t jerinstalin004/cancer-ml:latest .

    - name: Push Docker Image
      run: docker push jerinstalin004/cancer-ml:latest
